language: php
sudo: false

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3


before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer install --no-suggest --no-interaction

script:
  - vendor/bin/phpunit